### ISSUE TITLE
Cookfood

### ISSUE THREAD

**Issue by usuariozombie** [NutScript/falloutrp#2]
Is there any way to notice the player that he is hungry when (percent = 0.5), and why it doesn't kill you when it's 0?

**Comment by geferon** [comment]
To get the hunger percent: https://github.com/NutScript/falloutrp/blob/5fdfd2904037c6ece954b51df1b36233de71b213/plugins/cookfood/sh_plugin.lua#L51-L57

And, the function that kills the player when they're hungry is https://github.com/NutScript/falloutrp/blob/5fdfd2904037c6ece954b51df1b36233de71b213/plugins/cookfood/sh_plugin.lua#L232-L262
The only way of making it so players don't die when they're hungry would be either overriding that function or deleting it.

**Comment by usuariozombie** [comment]
Lol, I have tried the plugin even in a sample schema and it doesn't kill the player when the hunger o thirst metter is in 0.

**Comment by usuariozombie** [comment]
Geferon helped me, now it's ok, thanks.
